name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'

    - name: Install dependencies and build client
      run: |
        cd client
        npm install
        npm run build
        cd ../server
        npm install

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/bookcloudpub.pem
        chmod 600 ~/.ssh/bookcloudpub.pem
        ssh-keyscan -H 43.201.56.74 >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        ssh -i ~/.ssh/bookcloudpub.pem ubuntu@43.201.56.74 << 'EOF'
        cd /home/ubuntu/bookcloud-vue-inse
        git pull origin master
        cd server
        npm install
        pm2 restart all
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
