name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'

    - name: Install dependencies and build client
      run: |
        cd client
        npm install
        npm run build
        cd ../server
        npm install

    - name: Deploy to Server
      run: |
        ssh -i ~/.ssh/jungtaejoon-gmail.pem ec2-user@13.210.90.0 << 'EOF'
        cd /home/ec2-user/bookcloud-vue-inse
        git pull origin main
        cd server
        npm install
        pm2 restart all
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
